services:
  app:
    build:
      context: .
      target: gui
    ports:
      - "127.0.0.1:6080:6080"
    volumes:
      - ./docker-data:/data
    shm_size: 256mb
    init: true
  convert:
    profiles: [cli]
    build:
      context: .
      target: runtime
    volumes:
      - ./docker-data:/data
  test:
    profiles: [test]
    build:
      context: .
      target: test
